export const branchLabelOptions: Record<string, string> = {
  "153": "Makassar",
  "25": "Jakarta Selatan",
  "30": "Bandung",
  "31": "Banjarmasin",
  "32": "Yogyakarta",
  "36": "Surabaya",
  "265": "Bekasi",
  "1": "Alor Setar, Kedah",
  "2": "Ampang, Kuala Lumpur",
  "3": "Bangi, Selangor",
  "4": "Bdr Sunway, Selangor",
  "6": "Bt Berendam, Malacca",
  "10": "Ipoh, Perak",
  "11": "Johor Bahru, Johor",
  "12": "Kota Bharu, Kelantan",
  "13": "Kuala Terengganu, Terengganu",
  "14": "Kuantan, Pahang",
  "17": "Relau, Penang",
  "18": "Seremban, Negeri Sembilan",
  "19": "Sungai Petani, Kedah",
  "21": "Kota Kinabalu, Sabah",
  "22": "Kuching, Sarawak",
  "23": "Miri, Sarawak",
  "34": "Menara Public Gold, Kuala Lumpur",
  "135": "Tawau, Sabah",
};

export const branchOptionsId = [
  { value: "153", label: "Makassar" },
  { value: "25", label: "Jakarta Selatan" },
  { value: "30", label: "Bandung" },
  { value: "31", label: "Banjarmasin" },
  { value: "32", label: "Yogyakarta" },
  { value: "36", label: "Surabaya" },
  { value: "265", label: "Bekasi" },
];

export const branchOptionsMy = [
  { value: "1", label: "Alor Setar, Kedah" },
  { value: "2", label: "Ampang, Kuala Lumpur" },
  { value: "3", label: "Bangi, Selangor" },
  { value: "4", label: "Bdr Sunway, Selangor" },
  { value: "6", label: "Bt Berendam, Malacca" },
  { value: "10", label: "Ipoh, Perak" },
  { value: "11", label: "Johor Bahru, Johor" },
  { value: "12", label: "Kota Bharu, Kelantan" },
  { value: "13", label: "Kuala Terengganu, Terengganu" },
  { value: "14", label: "Kuantan, Pahang" },
  { value: "17", label: "Relau, Penang" },
  { value: "18", label: "Seremban, Negeri Sembilan" },
  { value: "19", label: "Sungai Petani, Kedah" },
  { value: "21", label: "Kota Kinabalu, Sabah" },
  { value: "22", label: "Kuching, Sarawak" },
  { value: "23", label: "Miri, Sarawak" },
  { value: "34", label: "Menara Public Gold, Kuala Lumpur" },
  { value: "135", label: "Tawau, Sabah" },
];
