/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PetunjukRouteImport } from './routes/petunjuk'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PgcodeRouteImport } from './routes/$pgcode'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PetunjukRoute = PetunjukRouteImport.update({
  id: '/petunjuk',
  path: '/petunjuk',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PgcodeRoute = PgcodeRouteImport.update({
  id: '/$pgcode',
  path: '/$pgcode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pgcode': typeof PgcodeRoute
  '/overview': typeof OverviewRoute
  '/petunjuk': typeof PetunjukRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pgcode': typeof PgcodeRoute
  '/overview': typeof OverviewRoute
  '/petunjuk': typeof PetunjukRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pgcode': typeof PgcodeRoute
  '/overview': typeof OverviewRoute
  '/petunjuk': typeof PetunjukRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$pgcode'
    | '/overview'
    | '/petunjuk'
    | '/register'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/admin/login'
    | '/admin/signup'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$pgcode'
    | '/overview'
    | '/petunjuk'
    | '/register'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/admin/login'
    | '/admin/signup'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$pgcode'
    | '/overview'
    | '/petunjuk'
    | '/register'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/admin/login'
    | '/admin/signup'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PgcodeRoute: typeof PgcodeRoute
  OverviewRoute: typeof OverviewRoute
  PetunjukRoute: typeof PetunjukRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pgcode': {
      id: '/$pgcode'
      path: '/$pgcode'
      fullPath: '/$pgcode'
      preLoaderRoute: typeof PgcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petunjuk': {
      id: '/petunjuk'
      path: '/petunjuk'
      fullPath: '/petunjuk'
      preLoaderRoute: typeof PetunjukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PgcodeRoute: PgcodeRoute,
  OverviewRoute: OverviewRoute,
  PetunjukRoute: PetunjukRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
